ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.service.tbterminal.plugins.DatabaseKt.configureDatabase
      - com.service.tbterminal.plugins.CorsKt.configureCors
      - com.service.tbterminal.plugins.SerializationKt.configureSerialization
      - com.service.tbterminal.plugins.SecurityKt.configureSecurity
      - com.service.tbterminal.plugins.StatusPagesKt.configureStatusPages
      - com.service.tbterminal.plugins.RoutingKt.configureRouting

postgres:
  url: jdbc:postgresql://localhost:5432/tb_terminal
  user: postgres
  password: "676767"
